# Generated by Django 2.1.7 on 2019-11-29 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('pID', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('pFName', models.CharField(blank=True, max_length=30)),
                ('pLName', models.CharField(blank=True, max_length=30)),
                ('pGender', models.CharField(blank=True, max_length=10)),
                ('pRace', models.CharField(blank=True, max_length=20)),
                ('pEthnicity', models.CharField(blank=True, max_length=20, null=True)),
                ('pStatus', models.CharField(blank=True, max_length=5)),
                ('pRemark', models.CharField(blank=True, max_length=255, null=True)),
                ('pAge', models.IntegerField(blank=True)),
                ('pImage', models.URLField()),
                ('dID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Doctor')),
            ],
        ),
    ]
