# Generated by Django 2.2.7 on 2019-11-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pFName',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
