# Generated by Django 2.2.7 on 2019-12-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20191130_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='resultImg',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pFName',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
