# Generated by Django 2.1.7 on 2019-12-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20191201_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pFName',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pGender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pLName',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pRace',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
